### ISSUE TITLE
Implement CSRF

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#213]
- [ ] find out how this will work with the react router
- [ ] should do csrf on per-request basis (rather than per-page-load)?
 - is this really more secure?
 - hash per request or secret per request?

**Comment by cadecairos** [comment]
cc/ @jbuck @simonwex

**Comment by jbuck** [comment]
We'll use [Double Submit Cookies](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#Double_Submit_Cookies) for CSRF protection. I don't think react router has anything to do with it, since only XHR requests send POST requests. We'll also need to make sure that the access_token route doesn't require CSRF.
