### ISSUE TITLE
Design login screen for desktop

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#27]
Finish design and present mocks/assets to @alicoding.

**Comment by cassiemc** [comment]
Here's where we are at with the login design. I want to make sure people know that I am suggesting we have two styles to serve the two different purposes of sign up vs. login. For signup (#29), we need to give people a bit more reassurance to hand over their email and commit to us, hence the headline and more heavily branded styles. 

For login, which you see here, people want to the utilitarian, really fast login process. Are you guys good with this approach @secretrobotron @thisandagain @alicoding?

![login-desktop-v3](https://cloud.githubusercontent.com/assets/1186326/6794410/c75731a0-d1a7-11e4-8dd6-943127dce650.jpg)

Here are the two styles side by side (which they never would be in the wild, fwiw):

![signup-vs-login](https://cloud.githubusercontent.com/assets/1186326/6794416/d61673c2-d1a7-11e4-828a-40e24098e34e.jpg)

**Comment by cassiemc** [comment]
Sounds like we are good with this approach so am going to close this up. Final designs are in the above comment and available for download here: https://www.dropbox.com/sh/kje9rwhkz4yizz6/AACUEmMG2Pj1CV9L9WIcAemba?dl=0

**Comment by secretrobotron** [comment]
:+1: 

@alicoding you got these assets?

**Comment by cassiemc** [comment]
Just one minor update – the password field needs the question mark icon (which leads to the password reset flow). Have updated the asset in dropbox and posting here:

![login-desktop-v3](https://cloud.githubusercontent.com/assets/1186326/6811759/9b1766de-d240-11e4-9c71-63d610e43925.jpg)

**Comment by cassiemc** [comment]
Another update: We've removed the question mark in lieu of a 'need help' link. If a user has a password, this link will take them to the password reset flow. If they do not have a password set, they will be taken to the user migration flow. Make sense @alicoding @Pomax @secretrobotron ?

![login-desktop-v4](https://cloud.githubusercontent.com/assets/1186326/6812405/0d142d9a-d245-11e4-8a48-3effaf096db6.jpg)

**Comment by cassiemc** [comment]
@vazquez Can you design R the above? (mainly, is the 'need help' link placement okay)

**Comment by vazquez** [comment]
I have 3 different suggestions. Some more radical than others.

1. First option is to place the link below the 'Log In' button. However, the button would need to become 100% width, which I know changes the design a bit. The end result however is something that looks more organized, and it never hurts to have a full width button, especially if the fields are already contained in a box. A quick look around of other apps show that it is pretty consistent to have a full width sign up/log in button. I would, however, add some more copy to make the call for help explicit. Something like "Need help logging in?"  
![screenshot 2015-03-24 22 15 46](https://cloud.githubusercontent.com/assets/1119821/6817139/57af1044-d273-11e4-9e54-bd62d7639e4c.png)  
2. The second option would be to place the link inside of the password field. My rationale for this is context. The help link really seems to be about password: "If a user has a password, this link will take them to the password reset flow. If they do not have a password set, they will be taken to the user migration flow". This way, the link doesn't feel lost and uncalled for at the bottom.  
![screenshot 2015-03-24 22 11 14](https://cloud.githubusercontent.com/assets/1119821/6817183/dbf7bd6a-d273-11e4-96a1-e794aa07c6b5.png)  
3. The 3rd option is the conservative approach. It involves leaving the design pretty much as it is, but aligning the help text to the baseline of the Log In button text. Also, aligning the help text to the log in button so that it gains some context to hold on to. The user would become less frustrated by associating the help link with the act of logging in. This is how I would assume the inner dialogue of a user would be: *Question from a user:* Need help with what? *Answer:* Ah, right. Logging in.  
![screenshot 2015-03-24 22 20 12](https://cloud.githubusercontent.com/assets/1119821/6817242/852de8d2-d274-11e4-9419-0a7271ca9d93.png)

**Comment by alicoding** [comment]
I really like option number 2!

**Comment by cassiemc** [comment]
Thanks for this @vazquez, much appreciated! I like option 2 as well, but it interferes with the field validation (checkmark and error icons). For that reason, I'm going with the 3rd option. 

Here are the final screens, which can be downloaded here: https://www.dropbox.com/sh/kje9rwhkz4yizz6/AACUEmMG2Pj1CV9L9WIcAemba?dl=0

Let's file any followup design work as additional issues. Thanks!

![01-login-blank](https://cloud.githubusercontent.com/assets/1186326/6830166/78bebe6c-d2ee-11e4-8520-3ab1c03f7875.jpg)
![02-username-verified](https://cloud.githubusercontent.com/assets/1186326/6830167/78c07522-d2ee-11e4-8772-edeb606b0b9b.jpg)
![03-password-verified](https://cloud.githubusercontent.com/assets/1186326/6830168/78c2621a-d2ee-11e4-9e2c-b1d217f21d0d.jpg)
