### ISSUE TITLE
Design sign-up screen for desktop

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#29]
Finish design and present mocks/assets to @alicoding.

**Comment by cassiemc** [comment]
This is where the design is at so far.

Note:
* I've streamlined the header bar so that it is more consistent (placement-wise) with the new desktop login designs
* I've reverted to the old use of the Webmaker logo (with new mozilla + Webmaker wordmark to emphasize the mozilla connection, as per @hpauljohnson) as a stand-in til we can update the branding. Note this new iteration has a smaller logo than previous iterations
* I've added a 'login' link to the top right (this was missing in the UX before) 
* the form now has a slightly wider default width for desktop, which allows for the signup button to be at the bottom right instead of full-width (on mobile responsive view, the Ts&Cs can be on top of a full-width 'sign up' button)
* @thisandagain did we get approval from legal to have no check-box (passive agreement) for the Ts&Cs?

![signup-desktop-v4](https://cloud.githubusercontent.com/assets/1186326/6786462/c7f35048-d162-11e4-82fa-4c7d28c993ca.jpg)

@vazquez design review please? https://redpen.io/br89c5f885f87fd81c

**Comment by thisandagain** [comment]
@cassiemc Re: no TOS confirm. We're good for now. :smile:

**Comment by vazquez** [comment]
Done design review @cassiemc

**Comment by cassiemc** [comment]
Thanks @vazquez! Calling this one closed, review points were minor and we can tweak / file additional QA bugs as needed. 

@alicoding, all yours!

cc / @secretrobotron

**Comment by alicoding** [comment]
@cassiemc can I ask you for a favour to put the design asset and or redpen to the implementation ticket before closing these? I'm a bit lost track with emails T_T sorry about that.

**Comment by cassiemc** [comment]
@alicoding It is the same asset listed in the comment above – https://github.com/mozilla/id.webmaker.org/issues/29#issuecomment-85121522

I'll repost the graphic here for clarity:
![signup-desktop-v4](https://cloud.githubusercontent.com/assets/1186326/6790428/e10d7c0a-d17d-11e4-9f99-90418a634fbc.jpg)
