### ISSUE TITLE
 Update teach-specific welcome email copy when signed up through teach - desktop

### ISSUE THREAD

**Issue by cassiemc** [mozilla/id.webmaker.org#35]
@hannahkane Do you have an idea of what you'd like the copy to be for this?

**Comment by secretrobotron** [comment]
Try https://teach.etherpad.mozilla.org/clubtransactionalemails
(from @hannahkane's answer [here](https://github.com/mozilla/id.webmaker.org/issues/4#issuecomment-83145664))

**Comment by hannahkane** [comment]
Thanks, @secretrobotron. That's the place!

**Comment by cassiemc** [comment]
Ok, thanks! Pasting content there:

CTAs: 

    Put your city on the map

    Check out our resources

 
Subject line: Welcome to the Mozilla Teach the Web Community!

Welcome!
 
Thanks for your interest in our global community of educators and activists who teach the web.

We'll help you discover:
 
·      Free and open resources to teach your learners about the web - start with these [link to activities page]
·      Opportunities to become a better facilitative leader and mentor
·      Tips on using Webmaker tools to create and teach
·      Best practices from peers and future collaborators

Start by putting your city on the map.

If  you're teaching the web in your local community, we want to know about  it. Adding your club, program or classroom to our community map is  simple, and allows us to send you locally relevant resources. If you  don't have a local group yet, let us know you're interested [link to  "interested" workflow], and one of our staff will be in touch with you  directly.
 
If you have any questions, we’re here to help. Our community loves to tweet and talk to new people – use the #teachtheweb hashtag to find us. 
 
Michelle Thorne
on behalf of the Mozilla Learning team

**Comment by cadecairos** [comment]
Is this just going to be a plaintext email?

**Comment by cadecairos** [comment]
> [link to "interested" workflow]

Where can I find this?

**Comment by hannahkane** [comment]
Plaintext is fine for now, as we don't have design resources to devote to creating a template.

The "interested" workflow is what happens when you click on the "find out more about us" link from the Clubs page header (currently viewable at http://teach.mofostaging.net/mozilla-web-clubs/). 

At the time we wrote the copy, we hadn't created the "interested" workflow yet, and now that I see it, it doesn't make sense to link to that modal.

Will replies to this email go to Michelle? If so, I'd suggest we change that sentence to, "If you don't have a local group yet, reply to this email to let us know you're interested, and we'll be in touch with you shortly."

@thornet - would that be okay with you?

**Comment by thornet** [comment]
Let's send replies to help@webmaker.org

cc @LucyeoH who can help us monitor.

**Comment by cassiemc** [comment]
FYI @cadecairos I started a design for this in https://github.com/mozilla/id.webmaker.org/issues/43

**Comment by secretrobotron** [comment]
Reminder: plain text email is fine for now.

**Comment by secretrobotron** [comment]
Moved copy to #4 to keep this work in one place now. cc @hannahkane
