### ISSUE TITLE
Persona in WebMaker ?

### ISSUE THREAD

**Issue by Ruwan-Ranganath** [mozilla/id.webmaker.org#420]
Why Webmaker project not use persona authentication for login . which use on other mozilla projects.

**Comment by cadecairos** [comment]
Hi @Ruwan-Ranganath, Webmaker used Persona for a while, but after many difficulties with it's confusing UX, we decided to stop using it. 

Using it again isn't going to happen because the service is being [discontinued this November](https://mail.mozilla.org/pipermail/persona-notices/2016/000005.html)
