### ISSUE TITLE
Document system design

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#5]
Need a digital artifact that articulates the login flow, including OAuth.
### Identity
- Are we identifying users by email, username, or both?
- How are we going to store user data?
- How will this system interact with user account in existing login system(s) (e.g. login3)?
### OAuth
- What are we whitelisting?
- What grant/permission setup are we choosing?
- What's the flow into and out of OAuth for teach.webmaker.org?
- JWT?
### Architecture
- Resource and Auth server: separate, or joined? (@jbuck to ask a couple people what's smartest)
- What front-end and back-end frameworks are we using?

Blocks #15
Blocks #18

**Comment by secretrobotron** [comment]
@jbuck @Pomax can you take a stab at answering these questions?

**Comment by thisandagain** [comment]
Bump on this as we'll need these questions clearly articulated for legal / security review.

/cc @simonwex @davidascher

**Comment by simonwex** [comment]
@jbuck is going to look at this today.

**Comment by jbuck** [comment]
* While we require an email address to sign-up for a Webmaker account, we will only be identifying users by their username
* We will store user data in a database, but I feel like this isn't the question being asked
* We will interact with the current login.wm.o database using the existing HTTP API for this heartbeat, and in the future migrate that user database out of login.wm.o
* For now, we'll only be whitelisting the teach site. I suspect we'd also be whitelisting webmaker.org and the mobile app in the future
* The OAuth flow for the teach site diagram is forth coming, but it is a carbon-copy of [Github's OAuth Web Application flow](https://developer.github.com/v3/oauth/#web-application-flow)
* We will not use JWT for the first iteration because we don't fully understand the security implications
* Resource and auth servers will be combined for now, but I believe we'll be separating them in a future heartbeat
* React for the front-end stuff and Hapi.js for the back-end

**Comment by secretrobotron** [comment]
:+1: woot!
What *is* the situation with the DB? Something specific (e.g. mongo), or relying on an abstraction layer? Easy to migrate/dump?

**Comment by jbuck** [comment]
Ah, I understand. Right now login.wm.o uses a mysql instance to store user data. It's easy enough to migrate to anything

**Comment by secretrobotron** [comment]
:+1: :+1:

**Comment by jbuck** [comment]
https://github.com/mozilla/id.webmaker.org/blob/master/docs/oauth.md is documentation for the OAuth2 API that teach will use

**Comment by secretrobotron** [comment]
cc @Pomax ^^

**Comment by davidascher** [comment]
Thx @jbuck, useful.

It would be good (probably not this week) to articulate how we can segment
the architecture so we can do network-level segmentation and intrusion
detection to protect the database containing passwords.

/cc @jdotpz

**Comment by jbuck** [comment]
@davidascher are you thinking along the lines of FxA where the authorization service that stores passwords is a completely separate service from the oauth service?

**Comment by davidascher** [comment]
I don't know enough about FxA to comment on that in particular.  What I
meant was that we should isolate the hashed-password-holding database (and
whatever service it is "close" to) so that we can a) enforce minimal ACLs
on that system (to minimize attack surface), b) eventually setup
network-level intrusion detection systems.
