### ISSUE TITLE
Add authentication step into "Add Your Club" workflow on teach site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/id.webmaker.org#51]
When an unauthed user clicks on "Add Your Club" from teach.mozilla.org/mozilla-web-clubs, they should be prompted to authenticate. Once authenticated, they should land back on /mozilla-web-clubs with the "Add Your Club" modal open.

The flow has already been built, using Persona as the authentication method, so this ticket is to replace Persona with the Webmaker auth experience.

**Comment by Pomax** [comment]
this is still blocked by the auth flow not having been fully worked out. getting both the backend and frontend up and running is still in progress, and when that dust settles we can start making "external" sites hook into the new authentication.

**Comment by toolness** [comment]
Arg, this is actually one place where an embedded (or pop-up) login modal rather than redirect makes things easier for us, b/c the code is already built to automatically move forward as soon as the user is logged in... coming back to the process after a redirect is harder because modals don't actually have their own URL yet. Ah, well.

**Comment by secretrobotron** [comment]
Just checked that this was done on mozteach.toolness.org. :+1:
