### ISSUE TITLE
Implement Login button on teach site

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#68]
It's using Persona atm, which mirrors the OAuth approach we're taking.

See #2 for design.

@hannahkane can you drop in mocks to show where it needs to go?

**Comment by hannahkane** [comment]
//cc @iamjessklein

**Comment by Pomax** [comment]
this is still blocked by the auth flow not having been fully worked out. getting both the backend and frontend up and running is still in progress, and when that dust settles we can start making "external" sites hook into the new authentication.

**Comment by Pomax** [comment]
I also opened https://github.com/mozilla/teach-api/issues/7 for @toolness to look at - once id.wmo is a closed oauth2 loop we should be able to set up the teach.wmo server with some app creds via @jbuck, and then get the [log in] button redirect to [id.wmo], which can then call back the teach.wmo server to inform it about whether or not login passed or failed.

**Comment by Pomax** [comment]
Okay, this is giving me way more headaches then I want, preventing me from actually visualising how this might work, so I need to get this straight:

- A user clicks on "login" on the teach.wmo site, which redirects to "<a href="https://id.webmaker.org/login/oauth/authorize?client_id=teach&state=blah&response_type=code">"

- For this to work, the `state` property needs to have some value that id.wmo can send on to the client's registered callback, so the page with the "login" link has to someone get a useful value in there.

- We can't get that a server-generated CSRF value, because there is no server generting the content, and we can't rely on a cookie, because the static pages have no server backing them, so there is no reason for them to have a cookie set.

Taking these things together, specifically for teach.wmo, the id.wmo redirect to teach.wmo's callback URL will end up being handled by a server that has no idea what value was used for `state`, so can never verify the callback belongs to a real login attempt.

How do we resolve that? /cc @toolness

**Comment by cassiemc** [comment]
The design in #2 is closed. The 1-color webmaker logomark svg is here: https://www.dropbox.com/s/4yndkmm0b1b92u3/logo-webmaker-flat.svg?dl=0 Here is the final treatment: 
![teach-login-button](https://cloud.githubusercontent.com/assets/1186326/6849429/906f3db4-d3a9-11e4-99c1-d74a214ea140.png)

**Comment by toolness** [comment]
> We can't rely on a cookie, because again the static pages have no server backing them, so there is no reason for them to have a cookie set.

Can we use `window.sessionStorage`? That's what we're currently using to store the token for the ol' Teach API.

**Comment by Pomax** [comment]
yarp, I set up some code that uses sessionStorage, with a diagram on how to close the loop on https://github.com/mozilla/teach.webmaker.org/pull/445

**Comment by toolness** [comment]
Hey, this has basically been implemented using a slightly different strategy documented in https://github.com/mozilla/teach.webmaker.org/issues/576. You can try it out for the time being at http://mozteach.toolness.org/ (I [hesitate](https://github.com/mozilla/teach.webmaker.org/issues/576#issuecomment-91233234) to replace the login on staging until the kinks are worked out because I don't want breakage to hamper our own testing of functionality on teach that requires login).

**Comment by iamjessklein** [comment]
YAYYYYYYYYYYYYY!!!!!!! 
:+1:  :postal_horn:
