### ISSUE TITLE
Consider better link copy for reset password link

### ISSUE THREAD

**Issue by cadecairos** [mozilla/id.webmaker.org#95]
It's currently "Need Help?" but I was surprised to find that it actually linked to the reset-password page. At first glance, I expected it to take me to support.mozilla.org - which leads me to believe it needs to be more clear in its messaging

**Comment by alicoding** [comment]
I just checked every social network sites that I know and all of them have link to **reset password** page and the link reads as "Forgot your password?" but in our case is more complicated than that because we want to use this same link to redirect based on two scenario:

1. If the user fill the username field then we will redirect them to **/reset-password** page if they have password before otherwise we will send them to **/migrate** page. 

2. If the user left the username field blank and click the link we will always redirect them to **/reset-password** page and we will decide from that page if they should continue with `reset password` flow or they should be send to `/migrate`.

Either way I agree that the message is not clear/obvious and we should update this to be a specific to password help link.

**Comment by cassiemc** [comment]
Yeah, I'd like to cover for all use-cases but I'm not keen on the complexities. I'm okay to change to "Forgot your password?"

From there, if a user puts in their username but had never actually set a password, we'd send them to the migration flow. Does that work for you @alicoding?

**Comment by alicoding** [comment]
Can I suggest we change the first page of user migration and reset password form to be the same then? that way we can write a logic to redirect them to the next flow based on their username...?

![](https://cloud.githubusercontent.com/assets/1186326/6807577/ace2416a-d225-11e4-8ed2-9fd950147f82.jpg)

![](https://cloud.githubusercontent.com/assets/1186326/6813828/4210376e-d24f-11e4-88aa-26db9ba17127.jpg)

**Comment by alicoding** [comment]
We have updated the text to "Forgot your password?" https://id.mofostaging.net/login the only thing left to do is based on my suggestion on this comment https://github.com/mozilla/id.webmaker.org/issues/95#issuecomment-88178824 but not sure if we should do it in this ticket. Maybe we can file that later if that is needed.
