### ISSUE TITLE
Investigate login referrals

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#97]
In #77 @adamlofting asks about the referral system. He needs it to be in tact so that we can tell how users use id.webmaker.org. We need to record referrals when users create or login to their accounts in the login user db so that @adamlofting can tell where they came from and what they intended to do.

* Do we have a system in place to record multiple referrals per user?
* If not, what do we need to build to support it?

/cc @cadecairos @jbuck

**Comment by adamlofting** [comment]
Exact spec of the old referral system isn't required at launch (thought I'd hate to lose it forever). That was primarily about marketing campaign referrals.

The thing I need for this new system is to know from looking at the id accounts database: 
* who are 'webmaker' users, and who are 'teach' users, and whor are 'system-x-as-yet-undefined' users
  * because it will soon be possible to have a webmaker id account without ever using or even looking at webmaker.
  * noting that users able to be more than one of those at a time.
* When a user first and last logged in via webmaker, teach, system-x-as-yet-undefined

This is because, someone who creates an account in order to login to teach, but who never visits or uses webmaker.org should not appear in webmaker.org metrics. And vice versa.

**Comment by adamlofting** [comment]
For the sake of language, it might help to talk about:

* Webmaker Accounts vs Webmaker Users as distinct numbers.

**Comment by jbuck** [comment]
So it looks like we can easily piggyback on the old referral code system. I propose that we add the oauth client_id as the referrer. 

@adamlofting would that be good enough for your purposes? Or would you need some sample data in the db to be sure?

**Comment by adamlofting** [comment]
Can we duplicate the old referral code table structure and setup an oauth_referrer table that works in the same way but just to log the client_id data? That would be cleanest for me.

And then if we add our marketing style campaign referrer codes back in the future, they can continue to use the old table (because at this point in time we'd be logging a client_id and a campaign code each time).

**Comment by jbuck** [comment]
@adamlofting and I had a quick chat and we decided that we should create a new table that captures oauth logins with the following structure:

`(UserId, client_id, timestamp)`

**Comment by adamlofting** [comment]
Closing this ticket, as this will be solved when we finish and merge: #334
